render-test-server-harness: fix tmux 1.8 compatibility

diff --git a/src/tests/render-test-server-harness b/src/tests/render-test-server-harness
--- a/src/tests/render-test-server-harness
+++ b/src/tests/render-test-server-harness
@@ -23,8 +23,12 @@ eval $@
 testret=$?
 # sleep 1 # let remote display update
 # capture screen
-if ! tmux capture-pane -ept $TMUX_PANE > $testname.capture; then
+if ! tmux capture-pane -et $TMUX_PANE; then
     printf "tmux capture-pane failed, erroring test\n" >&2
+    exit 99
+fi
+if ! tmux save-buffer $testname.capture; then
+    printf "tmux save-buffer failed, erroring test\n" >&2
     exit 99
 fi
 # return useful exitstatus from harnessed command
