Works in src/test on Linux, but not from top-level

diff --git a/src/tests/render-test b/src/tests/render-test
--- a/src/tests/render-test
+++ b/src/tests/render-test
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/sh -x
 
 #
 # Validate that mosh produces expected output, using screen captures
@@ -116,7 +116,16 @@ ssh_localhost_check()
 # main
 
 # Set up environment
-: ${srcdir:=$PWD}
+if [ -z "$srcdir" ]; then
+    : ${srcdir:=$PWD}
+else
+    srcdir="$(cd $srcdir && pwd)"
+    if [ $? -ne 0 ]; then
+	error "can't cd to srcdir: %s\n" "$srcdir"
+	exit 99
+    fi
+fi
+env
 
 if ! tmux_check; then
     test_skipped "tmux unavailable\n"
@@ -130,29 +139,29 @@ fi
 test_name=$1
 # XXX could use AM testsubdir macro instead
 test_dir=${test_name}.d
-test_script_base=${srcdir}/${test_name}
-rm -rf ${test_dir}
-mkdir ${test_dir}
+test_script_base="${srcdir}/${test_name}"
+rm -rf "${test_dir}"
+mkdir "${test_dir}"
 
 # Validate that we can run a test
-if [ ! -x ${test_script_base}.server-baseline ] \
-	      || [ -f ${test_script_base}.server-same -a ! -x ${test_script_base}.server-same ] \
-	      || [ -f ${test_script_base}.server-different -a ! -x ${test_script_base}.server-different ] \
-	      || [ -f ${test_script_base}.server-same -a ! -x ${test_script_base}.server-same ] \
-	      || [ -f ${test_script_base}.client -a ! -x ${test_script_base}.client ]; then
+if [ ! -x "${test_script_base}.server-baseline" ] \
+	      || [ -f "${test_script_base}.server-same" -a ! -x "${test_script_base}.server-same" ] \
+	      || [ -f "${test_script_base}.server-different" -a ! -x "${test_script_base}.server-different" ] \
+	      || [ -f "${test_script_base}.server-same" -a ! -x "${test_script_base}.server-same" ] \
+	      || [ -f "${test_script_base}.client" -a ! -x "${test_script_base}.client" ]; then
     test_error "test script(s) missing or not executable\n"
 fi
 
 
 # Run test(s).
 client_wrapper=env
-if [ -f ${test_script_base}.client ]; then
-    client_wrapper=${test_script_base}.client
+if [ -f "${test_script_base}.client" ]; then
+    client_wrapper="${test_script_base}.client"
 fi
 
 for server_test in baseline same different; do
-    testfile_name=${test_script_base}.server-${server_test}
-    if [ ! -x ${testfile_name} ]; then
+    testfile_name="${test_script_base}.server-${server_test}"
+    if [ ! -x "${testfile_name}" ]; then
 	continue
     fi
     log "Running $server_test.\n"
@@ -162,31 +171,34 @@ for server_test in baseline same different; do
 	tests=$server_test
     fi
     for run in $tests; do
+	# XXX need to quote server pathname here somehow
 	tested="../../scripts/mosh --client=../frontend/mosh-client --server=$PWD/../frontend/mosh-server --local --bind-server=127.0.0.1 127.0.0.1"
 	if [ "$run" = "baseline.direct" ]; then
 	    tested=""
 	fi
 	# Actually execute code under test
-	if ! tmux -C new-session $client_wrapper $tested ${srcdir}/render-test-server-harness ${PWD}/${test_dir}/${run} ${testfile_name} > ${test_dir}/${run}.tmux.log 2>&1; then
-	    test_error "tmux failure on test $run\n"
+	if ! tmux -C new-session $client_wrapper $tested "${srcdir}/render-test-server-harness" "${PWD}/${test_dir}/${run}" "${testfile_name}" > "${test_dir}/${run}.tmux.log" 2>&1; then
+	    test_error "tmux failure on test %s\n" "$run"
 	fi
 	# Check for server harness failures
-	if [ ! -s ${test_dir}/${run}.capture ] \
-	      || [ ! -s ${test_dir}/${run}.exitstatus ]; then
-	    test_error "server harness failure on test $run\n"
+	if [ ! -s "${test_dir}/${run}.capture" ] \
+	      || [ ! -s "${test_dir}/${run}.exitstatus" ]; then
+	    test_error "server harness failure on test %s\n" "$run"
 	fi
-	read server_rv < ${test_dir}/${run}.exitstatus
+	read server_rv < "${test_dir}/${run}.exitstatus"
 	if [ "$server_rv" -ne 0 ]; then
-	    test_error "server harness exited with status $server_rv\n"
+	    test_error "server harness exited with status %s\n" "$server_rv"
 	fi
     done
     # Compare captures
     if [ "$server_test" = baseline ]; then
-	files="${test_dir}/baseline.direct.capture ${test_dir}/baseline.capture"
+	file1="${test_dir}/baseline.direct.capture"
+	file2="${test_dir}/baseline.capture"
     else
-	files="${test_dir}/baseline.capture ${test_dir}/${server_test}.capture"
+	file1="${test_dir}/baseline.capture"
+	file2="${test_dir}/${server_test}.capture"
     fi
-    if diff -q $files; then
+    if diff -q "$file1" "$file2"; then
 	differ=n
     else
 	differ=y
@@ -199,6 +211,6 @@ for server_test in baseline same different; do
 	badresult=different
     fi
     if [ $differ != $desired ]; then
-	test_failure "Output is $badresult on test $server_test\n"
+	test_failure "Output is %s on test %s\n" "$server_test" " $badresult"
     fi
 done
